catalog/urls.py
from django.urls import path

from . import views
app_name = "catalog"
urlpatterns = [
    path("<int:id>", views.CategoryView.as_view(), name="category"),
    path("catalog_item/<int:id>", views.CatalogItemView.as_view(), name="catalog_item"),
    path("cart", views.CartView.as_view(), name="cart"),
    path("order", views.OrderView.as_view(), name="order"),
    path("clear_cart", views.ClearCartView.as_view(), name="clear_cart"),
    path("search", views.SearchView.as_view(), name="search"),
]

core/urls.py
from django.urls import path

from . import views
app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about", views.About.as_view(), name="about"),
    path("contact", views.Contact.as_view(), name="contact"),
    path("api/subscribe", views.SubscribeView.as_view(), name="subscribe"),
]

woods/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from woods import settings

urlpatterns = [
    path('', include('core.urls')),
    path('catalog/', include('catalog.urls')),
    path('admin_panel/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL)

catalog/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(max_length=50, verbose_name='Название категории', null=False)
    description = models.TextField(verbose_name='Описание категории', null=True, blank=True)
    title = models.CharField(max_length=50, verbose_name='Заголовок категории', null=True, blank=True)
    image = models.ImageField(upload_to='images/category/', verbose_name='Фото категории')
    number_on_main_page = models.PositiveSmallIntegerField(verbose_name="Номер на первой странице", null=True, blank=True)

    def __str__(self):
        return self.name


class Photo(models.Model):
    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"

    name = models.CharField(max_length=50, verbose_name='Название фото')
    image = models.ImageField(upload_to='images/all/', verbose_name='Фото')

    def __str__(self):
        return self.name


class MainAttribute(models.Model):
    class Meta:
        verbose_name = "Атрибут"
        verbose_name_plural = "Атрибуты"

    name = models.CharField(max_length=50, verbose_name='Название атрибута', null=False)
    title = models.CharField(max_length=50, verbose_name='Заголовок атрибута', null=False)
    additional_price = models.FloatField(verbose_name="Добавленная цена", default=0.0)
    thumbnail = models.ImageField(verbose_name="Логотип атрибута (мини)", upload_to='images/attribute/')
    item_photos = models.ManyToManyField(Photo, verbose_name="Фото товара с атрибутом")
    vendor_code = models.CharField(max_length=50, verbose_name='Артикул товара с атрибутом', null=False)
    delivery_days = models.IntegerField(verbose_name="Производство дней", null=True, blank=True)

    def __str__(self):
        return self.name


class SliderAttribute(models.Model):
    class Meta:
        verbose_name = "Атрибут слайдер"
        verbose_name_plural = "Атрибуты слайдер"
    name = models.CharField(max_length=50, verbose_name='Название атрибута слайдера', null=False)
    title = models.CharField(max_length=50, verbose_name='Заголовок атрибута слайдера', null=False)
    description = models.TextField(verbose_name='Описание слайдера')
    start_value = models.PositiveIntegerField(default=0, verbose_name="Начальное значение слайдера", null=False)
    stop_value = models.PositiveIntegerField(default=100, verbose_name="Конечное значение слайдера", null=False)

    def __str__(self):
        return self.name


class CategoryItem(models.Model):
    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ("id",)

    name = models.CharField(max_length=50, verbose_name='Название товара', null=False)
    description = models.TextField(verbose_name='Описание товара')
    price = models.FloatField(verbose_name="Цена", default=0.0)
    vendor_code = models.CharField(max_length=50, verbose_name='Артикул товара', null=False)
    main_attribute = models.ManyToManyField(MainAttribute, verbose_name="Основной атрибут", related_name='category_items', blank=True)
    slider = models.ManyToManyField(SliderAttribute, verbose_name="Слайдер атрибут", related_name='category_items', blank=True)
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.PROTECT)
    item_photos = models.ManyToManyField(Photo, verbose_name="Фото товара", blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата время заказа")
    description = models.TextField(verbose_name="Текст заказа")
    contact = models.TextField(verbose_name="Контакты")
    comment = models.TextField(verbose_name="Комментарий к заказу", null=True, blank=True)

catalog/views.py
import datetime

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView

from catalog.models import Category, CategoryItem, MainAttribute, SliderAttribute, Order
from core.mixins import TopMenuMixin
from woods import settings


class CategoryView(TopMenuMixin, ListView):
    model = CategoryItem
    template_name = "catalog/category.html"
    paginate_by = 8

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        items = qs.filter(category_id=self.kwargs['id'])
        return items

    def get_context_data(self, **kwargs):
        self.context.update(super().get_context_data(**kwargs))
        category = Category.objects.filter(id=self.kwargs['id']).first()
        self.context.update({"category": category})
        return self.context


class CatalogItemView(TopMenuMixin, View):
    template_name = "catalog/catalog_item.html"

    def get(self, request, *args, **kwargs):

        main_attribute_id = request.GET.get("attribute")
        catalog_item_id = kwargs["id"]
        catalog_item = CategoryItem.objects.get(id=catalog_item_id)

        if main_attribute_id:
            current_attribute = catalog_item.main_attribute.filter(id=main_attribute_id).get()
        else:
            current_attribute = catalog_item.main_attribute.all().first()
        sliders = catalog_item.slider.all()

        show_cart_add_button = True
        items = request.COOKIES
        for item in items.keys():
            if item.startswith("catalog_item"):
                attribute = item.split("&")[1:]
                if attribute[0] == str(catalog_item_id) and attribute[1] == str(current_attribute.id):
                    show_cart_add_button = False

        delivery_days = None
        if current_attribute.delivery_days:
            delivery_days = datetime.datetime.now().date() + datetime.timedelta(days=current_attribute.delivery_days)

        self.context.update({
            "catalog_item": catalog_item,
            "sliders": sliders,
            "current_attribute": current_attribute,
            "current_price": catalog_item.price + current_attribute.additional_price,
            "show_cart_add_button": show_cart_add_button,
            "delivery_days": delivery_days,
        })
        return render(request, template_name=self.template_name, context=self.context)


class CartView(TopMenuMixin, View):
    template_name = "catalog/cart.html"

    def get(self, request, *args, **kwargs):
        cart_is_empty = True
        items = request.COOKIES
        cart_items = []
        total_sum = 0
        for item in items.keys():
            if item.startswith("catalog_item"):
                attributes = item.split("&")[1:]
                item_text = "<br> - "
                for index, attribute_item in enumerate(attributes):
                    if index == 0:
                        catalog_item = CategoryItem.objects.filter(id=attribute_item).first()
                        item_text += f"{catalog_item.name}<br>"
                    elif index == 1:
                        main_attribute = MainAttribute.objects.filter(id=attribute_item).first()
                        item_text += f"Главный атрибут: {main_attribute.name}.<br>"
                    elif attribute_item.startswith("sl"):
                        slider_list = attribute_item.split("_")
                        slider_attribute = SliderAttribute.objects.filter(id=slider_list[1]).first()
                        item_text += f"Дополнительные параметры: {slider_attribute.name}, Значение {slider_list[2]}.<br>"

                total_sum += catalog_item.price + main_attribute.additional_price
                cart_items.append((catalog_item, main_attribute, item_text, catalog_item.price + main_attribute.additional_price))

        if len(cart_items) > 0:
            cart_is_empty = False

        self.context.update({"cart_is_empty": cart_is_empty, "cart_items": cart_items, "total_sum": total_sum})
        return render(request, template_name=self.template_name, context=self.context)


class OrderView(TopMenuMixin, View):
    template_name = "catalog/order.html"

    def post(self, request, *args, **kwargs):
        items = request.COOKIES
        cart_items = []
        cookie_items = []
        for item in items.keys():
            if item.startswith("catalog_item"):
                cookie_items.append(item)
                attributes = item.split("&")[1:]
                item_text = "\n - "
                for index, attribute_item in enumerate(attributes):
                    if index == 0:
                        catalog_item = CategoryItem.objects.filter(id=attribute_item).first()
                        item_text += f"Товар № {catalog_item.id} {catalog_item.name}, цена {catalog_item.price}.\n"
                    elif index == 1:
                        main_attribute = MainAttribute.objects.filter(id=attribute_item).first()
                        item_text += f"Главный атрибут {main_attribute.id} {main_attribute.name}, цена {main_attribute.additional_price}.\n"
                    elif attribute_item.startswith("sl"):
                        slider_list = attribute_item.split("_")
                        slider_attribute = SliderAttribute.objects.filter(id=slider_list[1]).first()
                        item_text += f"Доп атрибут {slider_attribute.id} {slider_attribute.name}, Значение {slider_list[2]}.\n"

                cart_items.append(item_text)

        order = Order.objects.create(contact=request.POST.get("phone_email"),
                                     comment=request.POST.get("comment"),
                                     description="; ".join(cart_items))
        try:
            send_mail(
                "Новый заказ на сайте",
                "Новый заказ на сайте.",
                f"{settings.EMAIL_FROM}",
                [f"{settings.EMAIL_TO}"],
            )
        except BaseException as e:
            print(f"err {e}")

        self.context.update(
            {"order_number": order.id,
             "order_date": order.date_created,
             "cart_item_count": 0,
             }
        )
        response = render(request, template_name=self.template_name, context=self.context)

        for i in cookie_items:
            response.delete_cookie(i)
        response.delete_cookie("cart_item_count")
        return response


class ClearCartView(View):

    def get(self, request, *args, **kwargs):

        items = request.COOKIES
        cookie_items = []
        for item in items.keys():
            if item.startswith("catalog_item"):
                cookie_items.append(item)

        response = HttpResponseRedirect(reverse("core:index"))

        for i in cookie_items:
            response.delete_cookie(i)
        response.delete_cookie("cart_item_count")
        return response


class SearchView(TopMenuMixin, ListView):
    model = CategoryItem
    template_name = "catalog/category.html"
    paginate_by = 8

    def get_queryset(self, **kwargs):
        q = self.request.GET.get("q")
        qs = super().get_queryset()
        items = qs.filter(description__icontains=q.lower().strip())
        return items

    def get_context_data(self, **kwargs):
        self.context.update(super().get_context_data(**kwargs))
        self.context.update({"search": self.request.GET.get("q")})
        return self.context

catalog/templates/catalog/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="main__content_wrapper">
        
        <!-- Start breadcrumb section -->
        <section class="breadcrumb__section breadcrumb__bg">
            <div class="container-fluid">
                <div class="row row-cols-1">
                    <div class="col">
                        <div class="breadcrumb__content">
                            <h1 class="breadcrumb__content--title text-white mb-10">Корзина</h1>
                            <ul class="breadcrumb__content--menu d-flex">
                                <li class="breadcrumb__content--menu__items"><a class="text-white" href="{% url 'core:index' %}">Главная</a></li>
                                <li class="breadcrumb__content--menu__items"><span class="text-white">Корзина</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End breadcrumb section -->

        <!-- cart section start -->
        <section class="cart__section section--padding">
            <div class="container-fluid">
                <div class="cart__section--inner">
                        {% if cart_is_empty %}
                            <h2>Корзина пуста...</h2><br>
                            <a class="continue__shopping--link" href="{% url 'core:index' %}#index_catalog_link">Продолжить покупки</a>
                        {% else %}
                            <h2 class="cart__title mb-40">Корзина</h2>
                            <div class="row">
                                <div class="col-lg-1">

                                </div>
                                <div class="col-lg-10">
                                    <div class="cart__table">
                                        <table class="cart__table--inner">
                                            <thead class="cart__table--header">
                                                <tr class="cart__table--header__items">
                                                    <th class="cart__table--header__list">Товар</th>

                                                    <th class="cart__table--header__list">Стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody class="cart__table--body">

                                            {% for item in cart_items %}
                                                <tr class="cart__table--body__items">
                                                    <td class="cart__table--body__list">
                                                        <div class="cart__product d-flex align-items-center">
<!--                                                            <button class="cart__remove&#45;&#45;btn" aria-label="search button" type="button"><svg fill="currentColor" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 24 24" width="16px" height="16px"><path d="M 4.7070312 3.2929688 L 3.2929688 4.7070312 L 10.585938 12 L 3.2929688 19.292969 L 4.7070312 20.707031 L 12 13.414062 L 19.292969 20.707031 L 20.707031 19.292969 L 13.414062 12 L 20.707031 4.7070312 L 19.292969 3.2929688 L 12 10.585938 L 4.7070312 3.2929688 z"/></svg></button>-->
                                                            <div class="cart__thumbnail">

                                                                <a href="{% url 'catalog:catalog_item' item.0.id %}?attribute={{ item.1.id }}"><img class="border-radius-5" src="{{ item.1.item_photos.all.1.image.url }}" alt="cart-product"></a>
                                                            </div>
                                                            <div class="cart__content">
                                                                <p>{{ item.2|safe }}</p>

                                                            </div>
                                                        </div>
                                                    </td>

                                                    <td class="cart__table--body__list">
                                                        <span class="cart__price end">{{ item.3 }}</span>
                                                    </td>
                                                </tr>
                                            {% endfor %}


                                                <tr class="cart__table--body__items">
                                                    <td class="cart__table--body__list">
                                                        <div class="cart__product d-flex align-items-center">
                                                            <div class="cart__thumbnail">

                                                            </div>
                                                            <div class="cart__content">
                                                                <p>ИТОГО: </p>
                                                            </div>
                                                        </div>
                                                    </td>

                                                    <td class="cart__table--body__list">
                                                        <span class="cart__price end">{{ total_sum }}</span>
                                                    </td>
                                                </tr>


                                            </tbody>
                                        </table>
                                        <div class="continue__shopping d-flex justify-content-between">
                                            <a class="continue__shopping--link" href="{% url 'core:index' %}#index_catalog_link">Продолжить покупки</a>
                                            <a class="continue__shopping--clear" href="{% url 'catalog:clear_cart' %}">Очистить корзину</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>
                            <br><br>
                            <form action="{% url 'catalog:order' %}" method="post">
                                {% csrf_token %}
                                <div class="row">

                                    <div class="col-lg-1">

                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="main checkout__mian">
                                                <div class="checkout__content--step section__contact--information">
                                                    <div class="section__header checkout__section--header d-flex align-items-center justify-content-between mb-25">
                                                        <h2 class="section__header--title h3">Информация для заказа</h2>
                                                    </div>
                                                    <div class="customer__information">
                                                        <div class="checkout__email--phone mb-12">
                                                            <input required class="checkout__input--field border-radius-5" name="phone_email" placeholder="Телефон или email для связи"  type="text">
                                                        </div>
                                                    </div>
                                                    <div class="order-notes mb-20">
                                                        <textarea class="checkout__notes--textarea__field border-radius-5" name="comment" id="order" placeholder="Оставьте любую дополнительную информацию" spellcheck="false"></textarea>
                                                    </div>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-1">

                                    </div>
                                    <div class="col-lg-2">
                                        <button class="quickview__cart--btn primary__btn" type="submit">Оформить заказ</button>
                                    </div>
                                </div>
                            </form>
                        {% endif %}

                </div>
            </div>
             <div class="container">

            </div>
        </section>
        <!-- cart section end -->

    </main>

{% endblock %}

catalog/templates/catalog/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="main__content_wrapper">
        
        <!-- Start breadcrumb section -->
        <section class="breadcrumb__section breadcrumb__bg">
            <div class="container">
                <div class="row row-cols-1">
                    <div class="col">
                        <div class="breadcrumb__content">
                            <h1 class="breadcrumb__content--title text-white mb-10">{% if category %}{{category.name}}{% elif search %}ПОИСК {{ search }}{% else %}Категория{% endif %}</h1>
                            <ul class="breadcrumb__content--menu d-flex">
                                <li class="breadcrumb__content--menu__items"><a class="text-white" href="{% url 'core:index' %}">Главная</a></li>
                                <li class="breadcrumb__content--menu__items"><span class="text-white">{% if category %}{{category.name}}{% elif search %}ПОИСК {{ search }}{% else %}Категория{% endif %}</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End breadcrumb section -->

        <!-- Start shop section -->
        <section class="shop__section section--padding">
            <div class="container">
                <div class="row">
                    <div class="col-12">

                        {% if not object_list %}
                        <div class="shop__header bg__gray--color d-flex align-items-center justify-content-between mb-30">
                            <div class="product__view--mode d-flex align-items-center">
                                <div class="product__view--mode__list product__short--by align-items-center d-lg-flex">
                                    <label class="product__view--label">{% if category %}В данной категории пока нет товаров {% elif search %}Ничего не нашлось, попробуйте еще раз{% else %}..{% endif %}</label>
                                </div>
                            </div>
                        </div>
                        {% else %}

                            <div class="shop__header bg__gray--color d-flex align-items-center justify-content-between mb-30">

                                <div class="product__view--mode d-flex align-items-center">

                                    <div class="product__view--mode__list product__short--by align-items-center d-none d-lg-flex">
<!--                                        <label class="product__view&#45;&#45;label">Сортировка :</label>-->
<!--                                        <div class="select shop__header&#45;&#45;select">-->
<!--                                            <select class="product__view&#45;&#45;select">-->
<!--                                                <option selected value="1">Сначала дороже</option>-->
<!--                                                <option value="2">Сначала дешевле</option>-->
<!--                                                <option value="3">Популярное</option>-->
<!--                                            </select>-->
<!--                                        </div>-->
                                    </div>

                                </div>
                                <p class="product__showing--count">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</p>
                            </div>


                            <div class="shop__product--wrapper">
                                   <div class="product__section--inner product__grid--inner">
                                        <div class="row row-cols-xl-4 row-cols-lg-3 row-cols-md-3 row-cols-2 mb--n30">
                                        {% for object in object_list %}

                                            <div class="col mb-30">
                                                <div class="product__items ">
                                                    <div class="product__items--thumbnail">
                                                        <a class="product__items--link" href="{% url 'catalog:catalog_item' object.id %}">
                                                            <img class="product__items--img product__primary--img" src="{{ object.item_photos.all.first.image.url }}" alt="product-img">
                                                            <img class="product__items--img product__secondary--img" src="{{ object.item_photos.all.first.image.url }}" alt="product-img">
                                                        </a>
                                                        <div class="product__badge">
                                                            <span class="product__badge--items sale">New</span>
                                                        </div>

                                                    </div>
                                                    <div class="product__items--content text-center">

                                                        <h3 class="product__items--content__title h4"><a href="{% url 'catalog:catalog_item' object.id %}">{{ object.name }}</a></h3>
                                                        <div class="product__items--price">
                                                            <span class="current__price">от {{ object.price|floatformat:2 }} ₽</span>
                                                        </div>
<!--                                                        <a class="product__items&#45;&#45;action__cart&#45;&#45;btn primary__btn" href="cart.html">-->
<!--                                                            <svg class="product__items&#45;&#45;action__cart&#45;&#45;btn__icon" xmlns="http://www.w3.org/2000/svg" width="13.897" height="14.565" viewBox="0 0 18.897 21.565">-->
<!--                                                                <path  d="M16.84,8.082V6.091a4.725,4.725,0,1,0-9.449,0v4.725a.675.675,0,0,0,1.35,0V9.432h5.4V8.082h-5.4V6.091a3.375,3.375,0,0,1,6.75,0v4.691a.675.675,0,1,0,1.35,0V9.433h3.374V21.581H4.017V9.432H6.041V8.082H2.667V21.641a1.289,1.289,0,0,0,1.289,1.29h16.32a1.289,1.289,0,0,0,1.289-1.29V8.082Z" transform="translate(-2.667 -1.366)" fill="currentColor"></path>-->
<!--                                                            </svg>-->
<!--                                                            <span class="add__to&#45;&#45;cart__text"> Добавить в корзину</span>-->
<!--                                                        </a>-->
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}

                                        </div>
                                    </div>
                                </div>




                            <div class="pagination__area bg__gray--color">
                                <nav class="pagination justify-content-center">
                                    <ul class="pagination__wrapper d-flex align-items-center justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li class="pagination__list"><a href="?page=1" class="pagination__item--arrow  link ">
                                                <svg xmlns="http://www.w3.org/2000/svg"  width="22.51" height="20.443" viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292"/></svg></a>
                                            <li>

                                            <li class="pagination__list"><a href="?page={{ page_obj.previous_page_number }}"><span class="pagination__item link">{{ page_obj.previous_page_number }}</span></a></li>
                                        {% endif %}
                                        <li class="pagination__list"><a href="#" class="pagination__item pagination__item--current">{{ page_obj.number }}</a></li>
<!--                                        <li class="pagination__list"><a href="shop.html" class="pagination__item link">3</a></li>-->
<!--                                        <li class="pagination__list"><a href="shop.html" class="pagination__item link">4</a></li>-->
                                        {% if page_obj.has_next %}

                                        <li class="pagination__list"><a href="?page={{ page_obj.next_page_number }}"><span class="pagination__item link">{{ page_obj.next_page_number }}</span></a></li>

                                        <li class="pagination__list"><a href="?page={{ page_obj.paginator.num_pages }}" class="pagination__item--arrow  link ">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.51" height="20.443" viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M268 112l144 144-144 144M392 256H100"/></svg></a>
                                            <li>
                                        {% endif %}

                                    </ul>
                                </nav>
                            </div>

                            {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!-- End shop section -->

    </main>

{% endblock %}